### ISSUE TITLE
MBF 2.1 Specification Tracking

### ISSUE THREAD

**Issue by madame-rachelle** [coelckers/gzdoom#1418]
**__Sectors__**
- [ ] Instant Death sector special: "alternate meaning" bit - https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#sectors

**__Lines__**
- [ ] Block Land Monsters line flag: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#block-land-monsters-line-flag
- [ ] Block Players line flag: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#block-players-line-flag
- [ ] Line scroll special variants: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#line-scroll-special-variants

**__Things__**
- [ ] Dehacked thing groups: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#dehacked-thing-groups
- [ ] Infighting: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#infighting
- [ ] Projectiles: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#projectile
- [ ] Splash: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#splash
- [ ] New thing flags: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#new-thing-flags
- [ ] Rip sound: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#rip-sound
- [ ] Fast speed: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#fast-speed
- [ ] Melee Range: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#melee-range

**__Weapons__**
- [ ] Weapon flags: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#weapon-flags
- [ ] Ammo pickup weapon autoswitch changes: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#ammo-pickup-weapon-autoswitch-changes
- [ ] Dehacked "ammo per shot" field: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#new-dehacked-ammo-per-shot-weapon-field

**__Frames__**
- [ ] Frame flags: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#frame-flags
- [ ] Args field for Dehacked states: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#new-args-fields-for-dehacked-states

- [ ] **__Dehacked code pointers__**: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#new-dehacked-codepointers
- [ ] `A_SpawnObject(type, angle, x_ofs, y_ofs, z_ofs, x_vel, y_vel, z_vel)`
- [ ] `A_MonsterProjectile(type, angle, pitch, hoffset, voffset)`
- [ ] `A_MonsterBulletAttack(hspread, vspread, numbullets, damagebase, damagedice)`
- [ ] `A_MonsterMeleeAttack(damagebase, damagedice, sound, range)`
- [ ] `A_RadiusDamage(damage, radius)`
- [ ] `A_NoiseAlert`
- [ ] `A_HealChase(state, sound)`
- [ ] `A_SeekTracer(threshold, maxturnangle)`
- [ ] `A_FindTracer(fov, rangeblocks)`
- [ ] `A_ClearTracer`
- [ ] `A_JumpIfHealthBelow(state, health)`
- [ ] `A_JumpIfTargetInSight(state)`
- [ ] `A_JumpIfTargetCloser(state, distance)`
- [ ] `A_JumpIfTracerInSight(state)`
- [ ] `A_JumpIfTracerCloser(state, distance)`
- [ ] `A_JumpIfFlagsSet(state, flags, flags2)` (note: this will require flag translation since GZDoom uses different flag bits)
- [ ] `A_AddFlags(flags, flags2)`
- [ ] `A_RemoveFlags(flags, flags2)`

**__Weapon Code Pointers__**
- [ ] `A_WeaponProjectile(type, angle, pitch, hoffset, voffset)`
- [ ] `A_WeaponBulletAttack(hspread, vspread, numbullets, damagebase, damagedice)`
- [ ] `A_WeaponMeleeAttack(damagebase, damagedice, zerkfactor, sound, range)`
- [ ] `A_WeaponSound(sound, fullvol)`
- [ ] `A_WeaponJump(state, chance)`
- [ ] `A_ConsumeAmmo(amount)`
- [ ] `A_CheckAmmo(state, amount)`
- [ ] `A_RefireTo(state, noammocheck)`
- [ ] `A_GunFlashTo(state, nothirdperson)`
- [ ] `A_WeaponAlert`

**__Miscellaneous__**
- [ ] compat flags: https://github.com/kraflab/mbf21/blob/master/docs/developer_spec.md#new-comp-flags (probably not needed)
- [x] ~~Demo stuff is irrelevant to GZDoom~~

**Comment by Gaerzi** [comment]
It's MBF 21 (as in, we're in the year 2021), not 2.1. ;)

**Comment by coelckers** [comment]
Like I already said on Discord, we're going to need help here from anybody who is interested in adding these features.  My time is too limited to do this all on my own, so anybody with an interest in seeing this added is welcome to contribute.

**Comment by coelckers** [comment]
Implementation is done.
I unchecked everything again so it can be tested. So far it's only an untested implementation

**Comment by kraflab** [comment]
Skillsaw prepared a wad that has the sector / line additions in it that might be convenient for testing some things, fyi:

[mbf21demo.zip](https://github.com/coelckers/gzdoom/files/6749462/mbf21demo.zip)

Xaser has been working on a comprehensive dehacked sampler, but it's still wip afaik.

**Comment by XaserAcheron** [comment]
Yeah, IRL has been nuking my brain lately so I haven't made much progress.

That said, here's what I have so far:
[mbf21demo_2021-07-01.zip](https://github.com/coelckers/gzdoom/files/6757476/mbf21demo_2021-07-01.zip)

It's the same as skillsaw's wad linked above, but it's also got replacements for the Chaingun, Rocket Launcher, and Plasma Rifle that test out a handful of the weapon/actor codepointers, so it may be useful for ensuring the basics are in place at least. Annotated source is [here](https://github.com/XaserAcheron/mbf21/tree/example/example/wadsrc), for the interested parties -- the dehacked patch is "compiled" so it's a bit opaque on its own.

I'll post updates to the wad here as they get done, though I'm not sure what the timeline is. Y'all are ahead of the curve here. ;P

**Comment by kraflab** [comment]
Small bugfix in A_SpawnObject here: https://github.com/kraflab/dsda-doom/pull/55

**Comment by Gaerzi** [comment]
> Annotated source is here, for the interested parties -- the dehacked patch is "compiled" so it's a bit opaque on its own.
This is something that I worry a bit about all these newfangled dehacked expansions. We're gonna get a lot of completely illegible actor code. With DECORATE, EDF, and the like, it's all human-readable, but turning it into dehacked is basically like running it through an obfuscator.

Maybe DECOHack should include the source code as a big comment section or something. I dunno, probably a discussion better had elsewhere...

**Comment by XaserAcheron** [comment]
IMO DECOHack's output isn't any less intelligible than a reasonably complex handcrafted DEH -- once you start getting into the weeds it gets real chaotic real quick (Batman Doom, anyone? :P ) -- if anything, it provides a new opportunity to provide a nice, clean source of some sort.

I might get into the habit of just copying over the decohack directory into a `src` dir in the zip itself 'cause why the carp not? -- having it be a standard feature would rock, though yeah, that's a bit offtopic now. :P

**Comment by coelckers** [comment]
Let's just say that for *any* machine generated data the source should always be provided as well as a matter of course. I have lost count of mods for various games - in particular Quake 2 and descendants where this omission led to mods that were lost once the original files ceased to be useful.

**Comment by coelckers** [comment]
BTW, I'd really appreciate if this stuff could be tested and results reported back.

**Comment by Gaerzi** [comment]
There's [this](https://www.doomworld.com/forum/topic/123082-heretic-invades-doom-two-small-maps-for-mbf21-ports/) as well as testing material.

**Comment by AtifArshad1995** [comment]
https://www.doomworld.com/forum/topic/123800-v100-vesper-mbf21-showcase-mod/

This gameplay mod by Xaser that uses MBF21 was just released today. The mod loads in GZDoom without errors but the weapons, other than the pistol, don't work at all. The projectiles don't seem to spawn.

**Comment by XaserAcheron** [comment]
For the record, I'm planning on doing a deeper dive into it and get some more specific bugs made (and maybe fix PRs? time will tell).

Some very rough notes off a 2-minute test playthrough:
- Sound indices for A_WeaponSound are off-by-one -- dehacked sound indices start at 1, not zero; thank Kilough for this weird Boom-ism :P
- Projectiles don't seem to be spawning correctly -- could be the args not being interpreted as dehacked fixed-point numbers? (i.e. in DEH a fixed field with the value 1.0 is actually represented as "65536" in the patch, not "1.0" or "1").

**Comment by MajorCooke** [comment]
`Block Land Monsters` is in.
